$ANSIBLE_VAULT;1.1;AES256
38376434343234653636616462633164323738616464323161343634623333626238663530326638
3663326533376637656137363736643130343162623265380a353361303561333439643466653430
32633538323264363336346563353436336530623235653835336136366232363634373430393235
3130663731343865650a616630343131343333343630373633383437653837376532616333383866
36633633386464613539396466613636386430353863623938346466363631353235306662333436
38316661633235663234353337336134626637313336366537626232393165363535353931666432
65386337343336633830613263393839363232353963323232383937303562636561663664303435
64616130363031346264356333363365623463343438666166316538326430353438363237303636
38653865616263626630633565343431633330326663363763653961666331353331636161393834
36623431656366353538626464623632343830386463313633323164366564303661353166346530
30613465333236636335333438316333303964333136646164386636613932633565613061343736
32323131616338336636393835646666616663383064353236366531336432616439613633303361
6363
