---
- name: install docker
  ansible.builtin.import_playbook: docker.yml

- name: install open-iscsi
  ansible.builtin.import_playbook: open-iscsi.yml

- name: install development k8s cluster with k3d
  ansible.builtin.import_playbook: k3d.yml

- name: install k3s
  ansible.builtin.import_playbook: k3s.yml

