$ANSIBLE_VAULT;1.1;AES256
37306333306636633262363739356631336566356564353039313334383234613165356263306164
3866623437666661386134373862343336653530663065380a316431653730396166633464383736
31646232626334313461393934386532303834626466316630343466303337666434616638353730
3234653234313333650a363866383161623236643566656539386264643339326665383730666661
33326461343366643430343766616333396330376336396430383830613936303363336266303039
62306361356133656139346662613562626665353539373137646562353533666530363539613964
34303330303532373339613834653362326262613133616661623635633066636433333163346538
34386237636133333831623136653132633636313435643332653137373837373564643031653863
64326435633137376563373161306261303466306530303930336135356666396333613637663966
63663163643332356365343933333966653730363530373363656530383331346133633035633664
65663539353665396261313832343132623961376464393633626663666236306635393239643531
65656232623437383133316536326462656537383361613865636137303130333739616434623532
6533
