$ANSIBLE_VAULT;1.1;AES256
39323061613630653236623937656662316535616361366664313163363335316139383564643932
6439343835343465356630666566663737643564393036370a373532313662666134333637663964
65386130623332393334336363333261303133303437336133373266373563396661316334333861
6664313737613039620a346266636134393466616563353066663664376131646566376631623534
32363235343639343534353438346364306234646639613832626662666332633633366132313464
64306433643465313133663538356532363932356236336462373935643330633462316464383338
66363531666462376363366561666461396438393331393431383065633638306633363261643232
61373032313830626537
